### ISSUE TITLE
Plugin should use parameters which are consistent with other plugins

### ISSUE THREAD

**Issue by farrp** [logstash-plugins/logstash-output-http#124]
Plugin should use parameters which are consistent with other plugins, particularly the SSL parameters.

cacert should be ssl_certificate_authorities
client_cert should be ssl_certificate
client_key should be ssl_key

Verify mode (no equivalent parameter in this plugin) should default to "none"

**Comment by bczifra** [comment]
Is this closed by https://github.com/logstash-plugins/logstash-output-http/pull/140 ?

**Comment by edmocosta** [comment]
Hi @bczifra! Yes, that's correct! I'm closing this issue as the SSL settings are already standardised for this plugin (https://github.com/logstash-plugins/logstash-output-http/pull/140). Thank you!
