### ISSUE TITLE
'host' header should contain port number

### ISSUE THREAD

**Issue by pchampin** [logstash-plugins/logstash-output-http#2]
With the following config:

    http {
      url => 'http://localhost:18001/playground/t1/'
      http_method => post
    }

I get the following HTTP query:

    POST /playground/t1/ HTTP/1.1
    host: localhost
    ...

The second line should be:

    host: localhost:18001

because a server listening on multiple ports needs this information to correctly answer the query.

Note that I can fix this by using `headers` in the logstash configuration to override the ``host`` header, but I shouldn't have to do it.

**Comment by andrewvc** [comment]
Thanks for the bug report! This is likely an issue with FTW, which has since been removed. Please upgrade to the latest version (1.1.0) and let us know if that doesn't fix it :)

**Comment by pchampin** [comment]
Indeed, the bug is fixed. Thanks :)
