### ISSUE TITLE
Expose Manticore::ClientProtocolException Underlying Exception

### ISSUE THREAD

**Issue by ayashjorden** [logstash-plugins/logstash-output-http#20]
Hi Logstash-Dev,
Running LS-1.5.4, http output version is 1.1.0.
Java:
```
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)
```
I'm using the HTTP output to push data to our BI tool, using this output config:
```javascript
output {
    if [@metadata][type] in [ "email_tracking", "email_sending" ]{
        http {
            url => "BI_TOOL_URL"
            content_type => "application/x-www-form-urlencoded"
            http_method  => "post"
            message => "%{http_message}"
            #ssl_certificate_validation => true
            format => "message"
            workers => 5
        }
    }
}
```

Checking the logs, I see a very vague exception messages:
```javascript
BI_TOOL_HOST:443 failed to respond {:url=>"https://BI_TOOL_URL", :method=>"log_failure", :body=>"VALID_JSON_BODY", :headers=>{"Content-Type"=>"application/x-www-form-urlencoded"}, :class=>"Manticore::ClientProtocolException", :backtrace=>nil, :level=>:error, :file=>"logstash/outputs/http.rb", :line=>"142"}
```

Looking at [Manticore](https://github.com/cheald/manticore/blob/53321bf7e7dceaa0264a55bc53880b9704310d0f/lib/manticore/response.rb) at line 54 shows me that the underlying exception is 'swalowed'.

I've tried running Logstash in debug mode, but didn't get any additional information regarding the cause for the HTTP request failure.

The majority of the messages I send to the BI too pass successfully, but I'd like to understand why i'm getting these failures.

Thank you,
Yarden

**Comment by thanthos** [comment]
Facing an issue that is similar to yours and being discussed in the following forum. In case the issue is overlapping. https://discuss.elastic.co/t/issue-logstashing-to-found-continued-discussion/32627

**Comment by frameloss** [comment]
I am also seeing this behavior when using the http output plugin. Watching a packet capture shows that logstash (manticore?) is trying to use a TCP session that has been closed, and receives a TCP reset from the webserver. I put an nginx proxy between logstash and the webservice I am communicating with, and cranked the keepalive_timeout to 600 and it seems to have helped the issue. In this case I am using a throttle filter, so events are infrequent which seems to be the only time there is an issue.

Packet capture of failure:

```
12:49:43.997868 IP 127.0.0.1.58683 > 127.0.0.1.80: Flags [P.], seq 2962871861:2962872165, ack 289751953, win 350, options [nop,nop,TS val 1903180146 ecr 1903105236], length 304
E..d..@.@............;.P...5.EC....^.X.....
qp9rqo..PUT /v2/room/4/topic?auth_token=zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz HTTP/1.1
Content-Type: application/json
Connection: Keep-Alive
Content-Length: 66
Host: 127.0.0.1
User-Agent: Manticore 0.4.4
Accept-Encoding: gzip,deflate

{"topic":"There are 2 open, 2 acknowledged, and 0 closed events."}
12:49:43.997899 IP 127.0.0.1.80 > 127.0.0.1.58683: Flags [R], seq 289751953, win 0, length 0
E..(.,@.@............P.;.EC.....P...w|..
```

**Comment by jamessemai** [comment]
I am seeing the same behaviour - I connected a logstash http output plugin to a logstash http input plugin, and after some time the http input plugin decides to close the connection with a FIN, ACK. The http output plugin ACKs that, but still tries to re-use the same connection a couple of minutes later.

Work-around for us has been to disable keepalive in the http output plugin (keepalive => false) - but obviously this is not ideal.

**Comment by jamessemai** [comment]
The work-around listed above improved things, but did not completely avoid the issue, so looked a bit deeper. 

It turns out that the keepalive timer of the logstash http input plugin is set to 20 seconds by default in [puma/const.rb] (https://github.com/puma/puma/blob/master/lib/puma/const.rb):

```
    # The default number of seconds for another request within a persistent
    # session.
    PERSISTENT_TIMEOUT = 20
```

This means the issue manifests itself whenever the client (http output plugin in my case) sends messages to the server (http input plugin in my case) at a rate that is lower than once every 20 seconds. So a better work-around is to set that timeout to a value that is guaranteed to be higher than longest expected time between consecutive events from the same server. 
In our case we ensured this by adding a heartbeat (using the heartbeat plugin), that sends events every PERSISTENT_TIMEOUT/2 seconds. This works well. 

Still, would be good if someone could look into fixing this in a better way.

Here is code to reproduce the erratic behavior:

```
$ cat httpKeepAlive.conf 
input {
    heartbeat {
        #interval => 15      #this works fine, lower than the default PERSISTENT_TIMEOUT interval
        interval => 25       #this causes errors, higher than the default PERSISTENT_TIMEOUT interval
        message => sequence
    }
    http {
        host => "127.0.0.1"
        port => 8888
        type => "http"
    }
}
output {
    if "http" in [type] {
        #heartbeat came in through http input, output to stdout
        stdout {
        }
    } else {
        #new heartbeat, output it via http output to http input
        http {
            mapping => {
                "message" => "%{clock}"
            }
            http_method => "post"
            url => "http://127.0.0.1:8888"
        }
    }
}
```

With interval set to 15 seconds (< PERSISTENT_TIMEOUT), everything works fine (as expected):

```
$ /opt/logstash/bin/logstash -f httpKeepAlive.conf 
Settings: Default filter workers: 1
Logstash startup completed
2016-01-13T09:07:31.089Z 127.0.0.1 1
2016-01-13T09:07:45.660Z 127.0.0.1 2
2016-01-13T09:08:00.663Z 127.0.0.1 3
2016-01-13T09:08:15.671Z 127.0.0.1 4
2016-01-13T09:08:30.661Z 127.0.0.1 5
```

With interval set to 25 seconds (> PERSISTENT_TIMEOUT) however, every other message is missed, illustrating the issue:

```
$ /opt/logstash/bin/logstash -f httpKeepAlive.conf 
Settings: Default filter workers: 1
Logstash startup completed
2016-01-13T09:08:54.059Z 127.0.0.1 1
127.0.0.1:8888 failed to respond {:url=>"http://127.0.0.1:8888", :method=>:post, :body=>"{\"message\":2}", :headers=>{"Content-Type"=>"application/json"}, :class=>"Manticore::ClientProtocolException", :backtrace=>nil, :level=>:error}
2016-01-13T09:09:43.682Z 127.0.0.1 3
127.0.0.1:8888 failed to respond {:url=>"http://127.0.0.1:8888", :method=>:post, :body=>"{\"message\":4}", :headers=>{"Content-Type"=>"application/json"}, :class=>"Manticore::ClientProtocolException", :backtrace=>nil, :level=>:error}
2016-01-13T09:10:33.681Z 127.0.0.1 5
```

Note: I am on logstash 2.1.1:

```
$ /opt/logstash/bin/logstash --version
logstash 2.1.1
```

**Comment by jamessemai** [comment]
Also the ``automatic_retries`` option does not seem to work here; no retries are being attempted if I add following to the http output config:
```
automatic_retries => 2

```

**Comment by bobrik** [comment]
Any news here?

**Comment by holmahenkel** [comment]
I am also experiencing random timeouts of HTTP requests towards external web services while using the HTTP output. I also tried `automatic_retries => "3"` with no effect. The `keepalive => "false"` option seem to improve things, as noted by @jamessemai .

Error shown in `/var/log/logstash/logstash.log`:
```
{:timestamp=>"2016-02-02T00:02:02.968000+0000",
:message=>"external.webhook.com:443 failed to respond",
:url=>"https://external.webhook.com", :method=>:post,
:body=>"{MESSAGE BODY}", :headers=>{"Content-Type"=>"application/json"},
:class=>"Manticore::ClientProtocolException",
:backtrace=>nil, :level=>:error}
```

System info:
```
$ java -version
java version "1.7.0_95"
OpenJDK Runtime Environment (IcedTea 2.6.4) (7u95-2.6.4-1~deb7u1)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)

$ /opt/logstash/bin/logstash --version
logstash 2.1.1
```

**Comment by krallin** [comment]
`automatic_retries` won't work if you're using `POST` as the `http_method` unless you also specify `retry_non_idempotent => true`. 

By default, [it appears the Logstash HTTP mixin retries GET only](https://github.com/logstash-plugins/logstash-mixin-http_client/blob/100ec72ff5bf0e13ffe115c49ea63db92ecdcaf0/lib/logstash/plugin_mixins/http_client.rb#L39-L46).

Note that the comments there are confusing (and "if `retry_non_idempotent` is set only GET, HEAD, PUT, DELETE, OPTIONS, and TRACE requests will be retried" appears to be flat out wrong), but [those options are all passthroughs to Manticore, which does have accurate documentation comments](https://github.com/cheald/manticore/blob/c8ae2cd5e8f6511224138a2cd057bf5492adfaa8/lib/manticore/client.rb#L134-L136).

Alternatively, what I've done is patch the client and also expose Manticore's `stale_check` option. There's a performance cost to doing this, but it does solve the issue: https://github.com/krallin/logstash-mixin-http_client/commit/68fa376a87eacf9ddb6e3fd84bf2ea8d8faf0b64

Manticore uses the underlying Apache Commons HTTP library, where there is some documentation aout the stale check parameter: http://hc.apache.org/httpclient-3.x/performance.html#Stale_connection_check

Hope this helps,

**Comment by andrewvc** [comment]
@krallin good research! Would you mind submitting that PR to logstash-mixin-http_client ? It's very weird that manticore disables that check by default given that Apache Commons enables it by default. I'll open an issue on manticore as that is not a sane default.

**Comment by andrewvc** [comment]
Hopefully the patch here: https://github.com/logstash-plugins/logstash-mixin-http_client/issues/18 will fix things for most people. @krallin 's patch is awesome ( and pointed me in the right direction ), but uses a deprecated method with less control over timing of stale checks.

**Comment by andrewvc** [comment]
This has been fixed in https://github.com/logstash-plugins/logstash-mixin-http_client/pull/18 . If you continue to experience problems please open a new issue at https://github.com/logstash-plugins/logstash-mixin-http_client/issues . You may also consider setting `validate_after_inactivity` to 0.

**Comment by cheald** [comment]
Okay, that gives me a better idea of what we're dealing with - Manticore won't auto-retry POST requests, so stale connections become especially apparent there. Let me read up a bit on best practices for stale connection handling.
