### ISSUE TITLE
Documentation issue: mapping example is wrong

### ISSUE THREAD

**Issue by steveniemitz** [logstash-plugins/logstash-output-http#30]
The documentation uses the example of:
`mapping => {"foo", "%{host}", "bar", "%{type}"}`

however, it should be an array:
`mapping => ["foo", "%{host}", "bar", "%{type}"]`

The former does not validate.

**Comment by magnusbaeck** [comment]
The `mapping` option is actually supposed to be a hash but an array like in your example also works. This buglet is fixed in #27.

**Comment by ph** [comment]
fixed in #27
