### ISSUE TITLE
Basic auth support

### ISSUE THREAD

**Issue by robinjoseph08** [logstash-plugins/logstash-output-http#37]
It looks like the `logstash-input-http` plugin has support for specifying a `user` and `password`, and it would be ideal if this plugin also had those same config fields. I know it's still possible to use the `headers` field and base64-encode `user:password`, but it would be nice to just specify it raw (from en environment variable for example) and the plugin sets the header for me.

**Comment by guyisra** [comment]
is there an update on this? Seems like http output with basic auth is meaningless without this.

**Comment by jondot** [comment]
@guyisra hopefully it should now be more meaningful :)

**Comment by guyisra** [comment]
@jondot Cool! If manticore supports this out of the box, wonder why wasn't auth used sooner. Thanks!

**Comment by uschtwill** [comment]
https://github.com/logstash-plugins/logstash-output-http/pull/42

Why did the PR get stuck?

**Comment by jordansissel** [comment]
Wilhelm, if you have interest in that PR, you can help by testing it,
reviewing the code, ensuring new tests are added, and reviewing new
documentation for the proposed feature.

**Comment by uschtwill** [comment]
Ah, my bad. It looked like it was just forgotten. Not sure I am qualified to test it, review it, and write tests for it. But I could write/review the documentation, sure. ^^ How?

**Comment by jsvd** [comment]
this was implemented in the http_client mixin in https://github.com/logstash-plugins/logstash-mixin-http_client/pull/28
