### ISSUE TITLE
Add retry feature to Plugin

### ISSUE THREAD

**Issue by githubmui** [logstash-plugins/logstash-output-http#38]

**Comment by lovromazgon** [comment]
+1 :+1:

**Comment by porcobravo** [comment]
I'm very interested in this feature as well. For a prototype is fine like it is, but I'm not sure I could justify using this plugin over custom code for production environment without this functionality.

By the way, could we consider it is the same issue as #28?

**Comment by andrewvc** [comment]
@githubmui @lovromazgon @porcobravo there is now a PR open adding retries. We expect to release it relatively soon. You can track it here: https://github.com/logstash-plugins/logstash-output-http/pull/51

**Comment by porcobravo** [comment]
Thanks @andrewvc 

Knowing that it will be pushed to production makes the decision a no-brainer.

**Comment by suyograo** [comment]
Fixed in #51
