### ISSUE TITLE
Ignore HTTP Response Codes

### ISSUE THREAD

**Issue by alfmatos** [logstash-plugins/logstash-output-http#49]
Hi. I'm using the http output plugin to execute a post request which can sometimes return non 2XX http response codes. The service sometimes returns a 409, which is safe to ignore.

The problem is that there is no way to ignore those 409 responses and the http output plugin logs every error request to the log, creating very large log files and a lot of non-useful debug.

The potential solution is to create an ignore_codes array that can be passed as an option into the plugin, so that it can safely ignore any required non-2xx codes.

Example:

```
output {
    http {
        url => "http://localhost:3000"
        http_method => "post"
        ignore_codes => [409]
        [...]
    }
}
```

The change is really simple. The diff can be found at https://github.com/alfmatos/logstash-output-http/commit/d9eeed7b5a5ca41792de6b201d6430bf60898091. If this is an acceptable approach, I can issue a PR.

**Comment by jordansissel** [comment]
Is the problem only "creating very large log files" ? Or is there something else?

**Comment by alfmatos** [comment]
Hi @jordansissel. There are a few issues that break our workflow.

- We're looking at some files with hundreds of megabytes
- It's triggering our monitoring alarms
- It's messing up our log analysis since we're using grep through very large files just to exclude the false positives (409)

**Comment by alfmatos** [comment]
@jordansissel just faced a major side effect which I think is caused by this: the failed posts seem to trigger retries that are kept in memory, eventually leading to a lot of memory consumption and cause an OOM. Since I was doing http output to do a direct elasticsearch query, it would block all of the logstash pipeline, since elasticsearch would stall.

Had to change the approach completely. Right now I'm in the process of debugging to see if it was really an HTTP Output + post to elasticsearch combo that causes recurrent OOM.

**Comment by andrewvc** [comment]
@alfmatos there is now a PR open adding this (among other things). We expect to release it relatively soon. You can track it here: https://github.com/logstash-plugins/logstash-output-http/pull/51

**Comment by alfmatos** [comment]
@andrewvc Thanks! Let's track it there then.
