### ISSUE TITLE
retryable_codes does not work in http output plugin

### ISSUE THREAD

**Issue by rkhapre** [logstash-plugins/logstash-output-http#55]
http output retryable_codes not working. It say invalid config

In my http output, i am applying this to retry the POST

retryable_codes => [531]

i get this below error message

ERROR logstash.outputs.http - Unknown setting 'r
etryable_codes' for http

Although in the documentation it is written this

https://www.elastic.co/guide/en/logstash/current/plugins-outputs-http.html#plugins-outputs-http-retryable_codes

**Comment by jsvd** [comment]
this must have been an old version of the plugin that didn't have this feature, I just tried and the pipeline started correctly:

```
~/logstash-6.1.1 % bin/logstash -e "input { generator { threads => 4 } } output { http { url => 'http://127.0.0.1:8080' http_method => post retryable_codes => [531] } }" --path.data=data2           
[2017-12-27T11:11:25,206][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"6.1.1"}
[2017-12-27T11:11:25,745][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
```
