### ISSUE TITLE
Add read timeout?

### ISSUE THREAD

**Issue by GaryRogers** [logstash-plugins/logstash-output-http#8]
I'm running into issues using this with InfluxDB 0.90. I _think_ I'm running into an issue where reads are blocking. Would it be possible to include a read_timeout variable and send that to FTW::Agent?

My config for reference:

```
http {
  http_method => "post"
  url => 'http://localhost:8086/write?db=stats_db&precision=m'
  format => "message"
  content_type => "application/x-www-form-urlencoded"
  message => 'application_log_events,facility=%{facility},level=%{level},host=%{host} value=1'
}
```

**Comment by andrewvc** [comment]
This has been added in the latest version (1.1.0) which is based on the http_client mixin. Try upgrading to 1.1.0 and setting one of [these three](https://github.com/logstash-plugins/logstash-mixin-http_client/blob/master/lib/logstash/plugin_mixins/http_client.rb#L79) options.

If you have any issues please open a new github issue.
