### ISSUE TITLE
Support Http compression with json_batch format

### ISSUE THREAD

**Issue by kishoreck** [logstash-plugins/logstash-output-http#87]
Version: Logstash 5.5 
Operating System: Centos

Config File :
http {
format => "json_batch"
http_method => "post"
codec => "json"
url => "https://myendpoint/"
pool_max_per_route => 2000
pool_max => 2000
automatic_retries => 2
http_compression => true
retry_non_idempotent => true
socket_timeout => 60
connect_timeout => 60
}

Issue:
- No gzip compression is applied when "format" is specified as "json_batch" and "http_compression" is set as true.

**Comment by kishoreck** [comment]
I opened a PR https://github.com/logstash-plugins/logstash-output-http/pull/88 - to add this support. Can you please advise me on the next step?

**Comment by jsvd** [comment]
this has been solved with https://github.com/logstash-plugins/logstash-output-http/pull/89, which is contained in 5.2.2 of this plugin
